### ISSUE TITLE
Specifying a default, non-JSON-serializable value causes Swagger page to crash

### ISSUE THREAD

**Issue by amickael** [apryor6/flask_accepts#69]
I am using flask-restx==0.2.0 with flask_accepts==0.16.4

Specifying `default` as a non serializable value like `datetime` in Marshmallow causes the Swagger page to fail to load. Here is my code:

### Marshmallow class
```python
class RespondSchema(Schema):
    data = fields.String(required=True)
    timestamp = fields.DateTime(default=datetime.utcnow)
```

### Route
```python
@api.route("/route")
class SomeRoute(Resource):
    @api.doc("some_route")
    @accepts(schema=AcceptSchema, api=api)
    @responds(schema=RespondSchema, api=api)
    def post(self):
        return SomeService.do_stuff(request.parsed_obj)
```

### Traceback
```
Traceback (most recent call last):
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/werkzeug/middleware/proxy_fix.py", line 169, in __call__
    return self.app(environ, start_response)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_restx/api.py", line 638, in error_router
    return original_handler(f)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_restx/api.py", line 636, in error_router
    return self.handle_error(e)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_restx/api.py", line 379, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_restx/api.py", line 402, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/Users/andrew.mickael/PycharmProjects/Financial-Ingestion-Service/venv/lib/python3.7/site-packages/flask_restx/representations.py", line 25, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
```

**Comment by ribeirojose** [comment]
Shouldn't `datetime.utcnow` be a function call such as in `datetime.utcnow()`?

**Comment by amickael** [comment]
> Just looking at a high level (not really sure what's the use case), shouldn't `datetime.utcnow` be a function call such as in `datetime.utcnow()`?

No, it’s a callable. If I were to specify utcnow() then all timestamps would default to the time the app was initialized.

**Comment by ribeirojose** [comment]
This is probably related to [this](https://github.com/apryor6/flask_accepts/blob/c951dd88ea06e8c6e47ecc2c47753458b6f1cdba/flask_accepts/utils.py#L163) part of `utils.py`. I would fire a PR this week but I'm not familiar with the code to extensively test this and write the tests. @apryor6 do you think changing that for something like the following would work? I don't really like the fact that we're pre-defining the format, but I think that could be workable as well. I'm also curious to know more about why map the default attr in marshmallow to the example attr in flask_restx (that's sheer curiosity, I'm not familiar with the implementation of those).

```python
    if hasattr(value, "default") and type(value.default) != ma.utils._Missing:
        fr_field_parameters["example"] = value.default
        if isinstance(value, ma.DateTime):
            fr_field_parameters["example"] = value.default().isoformat()
```

**Comment by amickael** [comment]
Thank you for your help @ribeirojose. This is not urgent at all, I can work around it for now.

**Comment by apryor6** [comment]
I played around with this a bit using a custom JSON encoder, but it appears that this object is not used in serialization with the Swagger doc creation process.

E.g.

```
import datetime
import json
from flask.json import JSONEncoder

class CustomJSONEncoder(JSONEncoder):
    """Custom encoder for handling default values from a function call"""

    def default(self, o):
        if callable(o):
            return str(o())
        return super().default(o)

json.dumps(datetime.datetime.utcnow, cls=CustomJSONEncoder)
```

Works just fine, but if I pass this encoder to the Flask app I still receive the same error you indicated.

```
app = Flask(__name__)
api = Api(app)
app.json_encoder = CustomJSONEncoder
```

I think this would require upstream changes to flask-restx unless I am unaware of existing functionality for handling this.

**Comment by amickael** [comment]
Thanks @apryor6, if this requires upstream changes then maybe we close this issue for now? I'll leave it up to you, I can easily work around this in the meantime.

**Comment by apryor6** [comment]
Yeah, I’ve inquired about this with the restx maintainers in their Gitter channel

**Comment by SteadBytes** [comment]
@amickael @apryor6 sorry for the slow response. The `flask-restx` Flask app setting `RESTX_JSON` can be used to configure additional parameters for JSON serialisation. Take a look at his and let me know if it works for you :smile: 

```python
from datetime import datetime
from json import JSONEncoder

from flask import Flask
from flask_accepts import accepts, responds
from flask_restx import Api, Resource
from marshmallow import Schema, fields


class CustomJSONEncoder(JSONEncoder):
    """Custom encoder for handling default values from a function call"""

    def default(self, o):
        if callable(o):
            return str(o())
        return super().default(o)


app = Flask(__name__)
# Realistically this would be set in a config file
app.config.update(RESTX_JSON={"cls": CustomJSONEncoder})

api = Api(app)

@api.route("/route")
class SomeRoute(Resource):
    @api.doc("some_route")
    @accepts(schema=AcceptSchema, api=api)
    @responds(schema=RespondSchema, api=api)
    def post(self):
        return SomeService.do_stuff(request.parsed_obj)
```

This setting seems to be completely undocumented so I apologise for that - I'll get it added to the documentation ASAP :+1:

**Comment by amickael** [comment]
Thanks @SteadBytes! I'll try that out, appreciate the help.

**Comment by apryor6** [comment]
Did this resolve your issue @amickael ?

**Comment by amickael** [comment]
Sorry for the late response @apryor6, that worked perfectly! Thanks everyone.

**Comment by apryor6** [comment]
Wonderful, no worries!
